// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleRepository;

namespace VehicleRepository.Migrations
{
    [DbContext(typeof(VehicleDBContext))]
    partial class VehicleDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VehicleModel.Vehicle", b =>
                {
                    b.Property<int>("ParkinfSlotNumber")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EnteryTime");

                    b.Property<DateTime>("ExitTime");

                    b.Property<int>("VehicleNumber");

                    b.Property<double>("chargesPerHr");

                    b.Property<string>("driverType");

                    b.Property<string>("parkingType");

                    b.Property<string>("vehicleType");

                    b.HasKey("ParkinfSlotNumber");

                    b.ToTable("Vehicle");
                });
#pragma warning restore 612, 618
        }
    }
}
